services:
  django:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    env_file: ".env"
    volumes:
      - .:/pysaxsay
    ports:
      - "8000:8000"
